const posts = [
  {
    id: 1,
    logo: "abarth.webp",
    name: "Abarth",
    alt: "Auto spare parts dubai",
  },
  {
    id: 2,
    logo: "ac.webp",
    name: "AC",
    alt: "Auto spare parts in uae",
  },
  {
    id: 3,
    logo: "acura.webp",
    name: "Acura",
    alt: "car battery replacement dubai",
  },
  {
    id: 4,
    logo: "aixam.webp",
    name: "Aixam",
    alt: "car battery sharjah sharjah",
  },
  {
    id: 5,
    logo: "alfa_romeo.webp",
    name: "Alfa Romeo",
    alt: "car battery sharjah",
  },
  {
    id: 6,
    logo: "ariel.webp",
    name: "Ariel",
    alt: "bmw battery replacement dubai",
  },
  {
    id: 7,
    logo: "arrinera.webp",
    name: "Arrinera",
    alt: "car battery sharjah sharjah",
  },
  {
    id: 8,
    logo: "aston_martin.webp",
    name: "Aston Martin",
    alt: "car battery change",
  },
  {
    id: 9,
    logo: "audi.webp",
    name: "Audi",
    alt: "battery replacement sharjah",
  },
  {
    id: 10,
    logo: "bentley.webp",
    name: "Bentley",
    alt: "car battery replacement",
  },
  {
    id: 11,
    logo: "bmw.webp",
    name: "BMW",
    alt: "car battery shop sharjah",
  },
  {
    id: 12,
    logo: "bugatti.webp",
    name: "Bugatti",
    alt: "car battery price dubai",
  },
  {
    id: 13,
    logo: "buick.webp",
    name: "Buick",
    alt: "Buick car parts",
  },
  {
    id: 14,
    logo: "cadillac.webp",
    name: "Cadillac",
    alt: "solite battery price in uae",
  },
  {
    id: 15,
    logo: "caterham.webp",
    name: "Caterham",
    alt: "caterham",
  },
  {
    id: 16,
    logo: "chevrolet.webp",
    name: "Chevrolet",
    alt: "car battery replacement near me",
  },
  {
    id: 17,
    logo: "chrysler.webp",
    name: "Chrysler",
    alt: "amaron battery dubai",
  },
  {
    id: 18,
    logo: "citroen.webp",
    name: "Citroen",
    alt: "car battery change dubai",
  },
  {
    id: 19,
    logo: "corvette.webp",
    name: "Corvette",
    alt: "car battery change dubai",
  },
  {
    id: 20,
    logo: "daihat.webp",
    name: "Daihatsu",
    alt: "battery change dubai",
  },
  {
    id: 21,
    logo: "dacia.webp",
    name: "Dacia",
    alt: "dacia spare parts",
  },
  {
    id: 22,
    logo: "daf.webp",
    name: "Daf",
    alt: "daf spare parts",
  },
  {
    id: 23,
    logo: "dodge.webp",
    name: "Dodge",
    alt: "car battery price",
  },
  {
    id: 24,
    logo: "drmotor.webp",
    name: "Drmotor",
    alt: "car battery price",
  },
  {
    id: 25,
    logo: "elfin.webp",
    name: "Elfin",
    alt: "Elfin parts",
  },
  {
    id: 26,
    logo: "ferrari.webp",
    name: "Ferrari",
    alt: "battery replacement dubai ",
  },
  {
    id: 27,
    logo: "fiat.webp",
    name: "Fiat",
    alt: "amaron car battery",
  },
  {
    id: 28,
    logo: "ford.webp",
    name: "Ford",
    alt: "amaron battery",
  },
  {
    id: 29,
    logo: "gmc.webp",
    name: "GMC",
    alt: "car battery replacement dubai",
  },
  {
    id: 30,
    logo: "greatwall.webp",
    name: "Great Wall",
    alt: "Auto spare parts in uae",
  },
  {
    id: 31,
    logo: "gaz.webp",
    name: "Gaz",
    alt: "Gaz spare parts",
  },
  {
    id: 32,
    logo: "geely.webp",
    name: "Geely",
    alt: "Geely parts",
  },
  {
    id: 33,
    logo: "gillet.webp",
    name: "Gillet",
    alt: "Gillet parts",
  },
  {
    id: 34,
    logo: "ginetta.webp",
    name: "Ginetta",
    alt: "Ginetta parts",
  },
  {
    id: 35,
    logo: "gumpert.webp",
    name: "Gumpert",
    alt: "Gumpert parts",
  },
  {
    id: 36,
    logo: "honda.webp",
    name: "Honda",
    alt: "car battery sharjah",
  },
  {
    id: 37,
    logo: "hummer.webp",
    name: "Hummer",
    alt: "bmw battery replacement dubai ",
  },
  {
    id: 39,
    logo: "hyundai.webp",
    name: "Hyundai",
    alt: "car battery change",
  },
  {
    id: 40,
    logo: "hennessey.webp",
    name: "Hennessey",
    alt: "hennessey car parts",
  },
  {
    id: 41,
    logo: "holden.webp",
    name: "Holden",
    alt: "Holden parts",
  },
  {
    id: 42,
    logo: "infiniti.webp",
    name: "Infiniti",
    alt: "battery replacement sharjah",
  },
  {
    id: 43,
    logo: "isuzu.webp",
    name: "Isuzu",
    alt: "car battery replacement",
  },
  {
    id: 44,
    logo: "jaguar.webp",
    name: "Jaguar",
    alt: "car battery shop sharjah",
  },
  {
    id: 45,
    logo: "jeep.webp",
    name: "Jeep",
    alt: "car battery price dubai",
  },
  {
    id: 46,
    logo: "kia.webp",
    name: "Kia",
    alt: "solite battery price in uae",
  },
  {
    id: 47,
    logo: "koenigsegg.webp",
    name: "Koenigsegg",
    alt: "Koenigsegg parts",
  },
  {
    id: 48,
    logo: "lancia.webp",
    name: "Lancia",
    alt: "Lancia parts",
  },
  {
    id: 49,
    logo: "lada.webp",
    name: "Lada",
    alt: "lada spare parts",
  },
  {
    id: 50,
    logo: "lotus.webp",
    name: "Lotus",
    alt: "lotus spare parts",
  },
  {
    id: 51,
    logo: "luxgen.webp",
    name: "Luxgen",
    alt: "Luxgen spare parts",
  },
  {
    id: 52,
    logo: "lamborghini.webp",
    name: "Lamborghini",
    alt: "car battery replacement near me",
  },
  {
    id: 53,
    logo: "land_rover.webp",
    name: "Land Rover",
    alt: "amaron battery dubai",
  },
  {
    id: 54,
    logo: "lexus.webp",
    name: "Lexus",
    alt: "car battery change dubai",
  },
  {
    id: 55,
    logo: "lincoln.webp",
    name: "Lincoln",
    alt: "battery change dubai",
  },
  {
    id: 56,
    logo: "mahindra.webp",
    name: "Mahindra",
    alt: "car battery price",
  },
  {
    id: 57,
    logo: "marutisuzuki.webp",
    name: "Maruti Suzuki",
    alt: "battery replacement dubai",
  },
  {
    id: 58,
    logo: "maserati.webp",
    name: "Maserati",
    alt: "amaron car battery",
  },
  {
    id: 60,
    logo: "maybach.webp",
    name: "Maybach",
    alt: "amaron battery",
  },
  {
    id: 61,
    logo: "mazda.webp",
    name: "Mazda",
    alt: "solite battery in uae",
  },
  {
    id: 62,
    logo: "mclaren.webp",
    name: "Mclaren",
    alt: "car battery dubai price",
  },
  {
    id: 63,
    logo: "mercedesbenz.webp",
    name: "Mercedes",
    alt: "dubai car battery",
  },
  {
    id: 64,
    logo: "mg.webp",
    name: "MG",
    alt: "amaron car battery in uae",
  },
  {
    id: 65,
    logo: "mini.webp",
    name: "Mini",
    alt: "uae car battery",
  },
  {
    id: 66,
    logo: "mitsubishi.webp",
    name: "Mitsubishi",
    alt: "battery uae",
  },
  {
    id: 67,
    logo: "morgan.webp",
    name: "Morgan Motor",
    alt: "acdelco battery price in uae",
  },
  {
    id: 68,
    logo: "fordmustang.webp",
    name: "Mustang",
    alt: "battery sharjah",
  },
  {
    id: 69,
    logo: "nissan.webp",
    name: "Nissan",
    alt: "car battery price dubai",
  },
  {
    id: 70,
    logo: "noble.webp",
    name: "Noble",
    alt: "Noble spare parts",
  },
  {
    id: 71,
    logo: "opel.webp",
    name: "Opel",
    alt: "car battery price uae",
  },
  {
    id: 72,
    logo: "pagani.webp",
    name: "Pagani",
    alt: "Pagani spare parts",
  },
  {
    id: 73,
    logo: "panoz.webp",
    name: "Panoz",
    alt: "Panoz spare parts",
  },
  {
    id: 74,
    logo: "perodua.webp",
    name: "Perodua",
    alt: "Perodua spare parts",
  },
  {
    id: 75,
    logo: "pininfarina.webp",
    name: "Pininfarina",
    alt: "battery change dubai",
  },
  {
    id: 76,
    logo: "peugeot.webp",
    name: "Peugeot",
    alt: "battery change dubai",
  },
  {
    id: 77,
    logo: "porsche.webp",
    name: "Porsche",
    alt: "solite battery price uae",
  },
  {
    id: 78,
    logo: "proton.webp",
    name: "Proton",
    alt: "amaron battery price uae",
  },
  {
    id: 79,
    logo: "renault.webp",
    name: "Renault",
    alt: "amaron battery dubai",
  },
  {
    id: 80,
    logo: "reva.webp",
    name: "Reva",
    alt: "car battery",
  },
  {
    id: 81,
    logo: "rimac.webp",
    name: "Rimac",
    alt: "dubai car battery replacement",
  },
  {
    id: 82,
    logo: "rollsroyce.webp",
    name: "Rolls Royce",
    alt: "car battery",
  },
  {
    id: 83,
    logo: "ruf.webp",
    name: "Ruf",
    alt: "car battery",
  },
  {
    id: 84,
    logo: "saab.webp",
    name: "Saab",
    alt: "saab spare parts",
  },
  {
    id: 85,
    logo: "seat.webp",
    name: "Seat",
    alt: "amaron battery dubai",
  },
  {
    id: 86,
    logo: "scion.webp",
    name: "Scion",
    alt: "amaron battery dubai",
  },
  {
    id: 87,
    logo: "scania.webp",
    name: "Scania",
    alt: "amaron battery dubai",
  },
  {
    id: 88,
    logo: "shelby.webp",
    name: "Shelby",
    alt: "Auto spare parts in uae",
  },
  {
    id: 89,
    logo: "skoda.webp",
    name: "Skoda",
    alt: "car battery replacement dubai",
  },
  {
    id: 90,
    logo: "smart.webp",
    name: "Smart",
    alt: "car battery change dubai",
  },
  {
    id: 91,
    logo: "spyker.webp",
    name: "Spyker",
    alt: "car battery dubai",
  },
  {
    id: 92,
    logo: "ssangyong.webp",
    name: "Ssangyong",
    alt: "car batteries dubai",
  },
  {
    id: 93,
    logo: "ssc.webp",
    name: "SSC",
    alt: "car battery",
  },
  {
    id: 94,
    logo: "subaru.webp",
    name: "Subaru",
    alt: "car battery sharjah",
  },
  {
    id: 95,
    logo: "suzuki.webp",
    name: "Suzuki",
    alt: "battery replacement dubai",
  },
  {
    id: 96,
    logo: "supercar.webp",
    name: "Supercar",
    alt: "battery replacement dubai",
  },
  {
    id: 97,
    logo: "tata.webp",
    name: "Tata",
    alt: "battery replacement sharjah",
  },
  {
    id: 98,
    logo: "tatra.webp",
    name: "Tatra",
    alt: "battery replacement sharjah",
  },
  {
    id: 99,
    logo: "tramontana.webp",
    name: "Tramontana",
    alt: "battery replacement sharjah",
  },
  {
    id: 100,
    logo: "troller.webp",
    name: "Troller",
    alt: "Troller spare parts",
  },
  {
    id: 101,
    logo: "tvr.webp",
    name: "TVR",
    alt: "TVR spare parts",
  },
  {
    id: 102,
    logo: "tesla.webp",
    name: "Tesla",
    alt: "battery sharjah",
  },
  {
    id: 103,
    logo: "toyota.webp",
    name: "Toyota",
    alt: "car battery dubai price",
  },
  {
    id: 104,
    logo: "uaz.webp",
    name: "UAZ",
    alt: "UAZ spare parts",
  },
  {
    id: 105,
    logo: "vandenbrink.webp",
    name: "Vandenbrink",
    alt: "Vandenbrink spare parts",
  },
  {
    id: 106,
    logo: "vauxhall.webp",
    name: "Vauxhall",
    alt: "Vauxhall spare parts",
  },
  {
    id: 107,
    logo: "vector.webp",
    name: "Vector",
    alt: "Vector spare parts",
  },
  {
    id: 108,
    logo: "venturi.webp",
    name: "Venturi",
    alt: "Venturi spare parts",
  },
  {
    id: 109,
    logo: "volkswagon.webp",
    name: "Volkswagen",
    alt: "car battery",
  },
  {
    id: 110,
    logo: "volvo.webp",
    name: "Volvo",
    alt: "sharjah car battery",
  },
  {
    id: 111,
    logo: "wiesmann.webp",
    name: "Wiesmann",
    alt: "sharjah car battery",
  },
  {
    id: 112,
    logo: "zagato.webp",
    name: "Zagato",
    alt: "Zagato spare parts",
  },
  {
    id: 113,
    logo: "zaz.webp",
    name: "Zaz",
    alt: "Zaz spare parts",
  },
  {
    id: 114,
    logo: "zil.webp",
    name: "Zil",
    alt: "zill spare parts",
  },
]

export default posts
